import { type Metadata } from 'next'
<<<<<<< HEAD
import './globals.css'
import { NextAuthProvider } from "./providers";

export const metadata: Metadata = {
  title: 'Loop',
  description: 'Minimal Satck Clone',
=======
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { ConvexClientProvider } from '@/lib/convex'
import Header from '@/components/Header'
import { SyncUser } from '@/components/SyncUser'


export const metadata: Metadata = {
  title: 'Type2geda',
  description: 'Generated by create next app',
>>>>>>> 0e4d343317a51763be69c43dc79d1eb46ac47b72
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="type-theme">
      <body suppressHydrationWarning className={`antialiased`}>
<<<<<<< HEAD
        <NextAuthProvider>
          <main>
            {children}
          </main>
        </NextAuthProvider>
=======
      <ClerkProvider>
        <ConvexClientProvider>
          <SyncUser />
          <header>
            <Header>
              <button></button>
            </Header>
          </header>
          <main>
            {children}
          </main>
        </ConvexClientProvider>
      </ClerkProvider>
>>>>>>> 0e4d343317a51763be69c43dc79d1eb46ac47b72
      </body>
    </html>
  )
}