import { type Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { ConvexClientProvider } from '@/lib/convex'
import Header from '@/components/Header'
import { SyncUser } from '@/components/SyncUser'


export const metadata: Metadata = {
  title: 'Type2geda',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="type-theme">
      <body suppressHydrationWarning className={`antialiased`}>
      <ClerkProvider>
        <ConvexClientProvider>
          <SyncUser />
          <header>
            <Header>
              <button></button>
            </Header>
          </header>
          <main>
            {children}
          </main>
        </ConvexClientProvider>
      </ClerkProvider>
      </body>
    </html>
  )
}